services:
  web:
    build: web
    ports:
    - 8080
  api:
    build: api
    ports:
    - 3000
    environment:
      - PORT=3000
      - DB_PASSWORD=passw0rd
      - DB_USER=root
    labels:
      1!"·$!31: ñÇ*^.,
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=okteto
