endpoints:
  - path: /
    service: web
    port: 8080
  - path: /api
    service: api
    port: 3000
  - path: /username
    service: api
    port: 3000
services:
  web:
    build: web
    ports:
    - 8080
    environment:
      - OKTETO_USERNAME=$OKTETO_USERNAME
  api:
    build: api
    ports:
    - 3000
    environment:
      - PORT=3000
      - DB_PASSWORD=passw0rd
      - DB_USER=root
      - OKTETO_USERNAME=$OKTETO_USERNAME
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=okteto